# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20171112_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontacts',
            name='owner',
        ),
    ]
