# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 23:18
from __future__ import unicode_literals

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_usercontacts_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='phone',
            field=models.IntegerField(default=1234567, max_length=20, validators=[contacts.validators.is_valid_number]),
            preserve_default=False,
        ),
    ]
