# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 22:24
from __future__ import unicode_literals

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20180423_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='phone',
            field=models.IntegerField(validators=[contacts.validators.is_valid_number]),
        ),
    ]
