# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('MOT', 'motivational'), ('SPR', 'spiritual'), ('LOL', 'funny')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
